[tool.poetry]
name = "zaccount"
version = "0.1.0"
description = ""
authors = ["zweix123 <11680125+zweix123@user.noreply.gitee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
dryads = "^2.0.0"
openpyxl = "^3.1.5"
types-openpyxl = "^3.1.5.20250602"


[tool.poetry.group.dev.dependencies]
rich = "^14.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
